#!/usr/bin/env python3
"""Find the comments a codebase would be better without.

    python audit_comments.py path/to/repo
    python audit_comments.py path/to/repo --category restates,todo
    python audit_comments.py path/to/repo --format json
    python audit_comments.py path/to/repo --max-block 4 --max-inline 2

Reports what is mechanically detectable: markers, commented-out code, section labels, generated
boilerplate, openers that restate a declaration, comments whose words are already in the line
below, and blocks past the shape limit.

It deliberately does not judge whether a surviving comment is a worthwhile *why* - only a reader
can do that. What it does instead is rank files by prose density, so the reading starts where it
pays. Exits non-zero when anything in a failing category is found.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, asdict
from pathlib import Path

# How each language opens a comment. Type annotations and pragmas are filtered separately, so a
# language whose docblocks carry types is still handled.
SYNTAX = {
    "c_like": {
        "line": "//", "block": ("/*", "*/"),
        "suffixes": {".php", ".js", ".jsx", ".ts", ".tsx", ".java", ".c", ".h", ".cpp", ".hpp",
                     ".cs", ".go", ".rs", ".swift", ".kt", ".scala", ".dart", ".sass", ".scss"},
    },
    "hash": {
        "line": "#", "block": None,
        "suffixes": {".py", ".rb", ".sh", ".bash", ".zsh", ".yml", ".yaml", ".toml", ".tf",
                     ".tfvars", ".pl", ".r", ".ex", ".exs", ".nix", ".just"},
        "names": {"Dockerfile", "Makefile", "Justfile", ".env.example", ".dockerignore",
                  ".gitignore", "Procfile"},
    },
    "sql": {"line": "--", "block": ("/*", "*/"), "suffixes": {".sql"}},
    "css": {"line": None, "block": ("/*", "*/"), "suffixes": {".css", ".less"}},
    "html": {"line": None, "block": ("<!--", "-->"), "suffixes": {".html", ".xml", ".vue", ".svelte"}},
}

SKIP_DIRS = {".git", "node_modules", "vendor", "dist", "build", "target", "__pycache__",
             ".venv", "venv", ".next", ".nuxt", "coverage", "storage", ".terraform"}

# Generated files: their comments are not the team's to answer for.
GENERATED = re.compile(
    r"(@generated|do not edit|DO NOT EDIT|autogenerated|auto-generated|Code generated by)",
)

# Load bearing, never counted as prose: a linter or type checker fails without them.
PRAGMA = re.compile(
    r"^\s*[*#/\-<!]*\s*("
    r"@(param|return|returns|var|type|template|extends|implements|mixin|use|property|method|throws|"
    r"deprecated|phpstan|psalm|ts-|eslint|typescript|see|inheritdoc|internal|override|nodoc)"
    r"|type:|noqa|pragma|pylint|mypy|ruff|prettier|eslint|stylelint|go:|cgo|nolint|"
    r"#\[|coding[:=]|-\*-|shellcheck|checkov|tflint|hadolint|trivy|yamllint|language=|"
    # Directives a build reads. A Dockerfile's syntax= line and a shebang look like comments and
    # are not: deleting one changes what runs.
    r"syntax=|escape=|check=|frozen_string_literal|warn_indent|!/|!\s*/usr|source\s|deno-|"
    r"biome-|v8-|webpack|vite-|rollup|swc-|istanbul|c8\s|jest|vitest-environment)",
    re.IGNORECASE,
)

# Text that is code rather than prose, so a commented-out line rather than an explanation.
CODE_SHAPED = re.compile(
    r"(^\s*[\w$@.\[\]]+\s*(=|:=|=>|->|\+=|\|\|=)"          # an assignment
    r"|^\s*(return|import|from|const|let|var|def|func|class|public|private|if|for|while|"
    r"foreach|echo|print|console\.|System\.|await|async|require|use|package)\b"
    r"|\)\s*[;{]\s*$|^\s*[}\])];?\s*$)"                     # a closing line
)

SECTION_LABEL = re.compile(r"^[\s\-=*_#]*[A-Za-z][A-Za-z /&]{0,28}[\s\-=*_#]*$")
DECLARATION = re.compile(
    r"(?:class|interface|trait|enum|struct|function|func|def|const|type|component|"
    r"public|private|protected|export)\s+(\w+)"
)
BANNER = re.compile(r"^[\s\-=*_#~+]{6,}$")
MARKER = re.compile(r"\b(TODO|FIXME|XXX|HACK|WIP|REFACTOR)\b")

STOP = set("a an the of to is are was were and or it its that this these those for in on at with "
           "as be been by from not what which who when where how so rather than one two only every "
           "each no nothing can could would will has have had do does did if then else but any all "
           "both same other more most we you they our their there here just also into over under".split())

FAILING = {"todo", "commented_code", "section_label", "banner", "restates", "generated_boilerplate"}


@dataclass
class Note:
    path: str
    line: int
    category: str
    height: int
    text: str
    following: str


def words(text: str) -> list[str]:
    spaced = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", text)
    return [w for w in re.findall(r"[A-Za-z]+", spaced.lower()) if w not in STOP and len(w) > 2]


def syntax_for(path: Path) -> dict | None:
    for spec in SYNTAX.values():
        if path.suffix in spec.get("suffixes", set()) or path.name in spec.get("names", set()):
            return spec
    return None


def is_example_file(path: Path) -> bool:
    """Example files are allowed to explain; they are still not allowed to ramble."""
    name = path.name.lower()
    return "example" in name or "sample" in name or name.endswith(".dist")


def strip_marker(line: str, spec: dict) -> str:
    """The text of one comment line, or empty for a line that is only syntax.

    The closer goes first: `*/` survives a leading-star strip as a bare slash, which then counts
    as a line of prose and makes every block read one taller than it is.
    """
    text = line.strip()
    for closer in filter(None, [spec["block"][1] if spec["block"] else None]):
        text = text.replace(closer, "")
    for opener in filter(None, [spec["block"][0] if spec["block"] else None, spec["line"]]):
        if text.startswith(opener):
            text = text[len(opener):]
    text = re.sub(r"^\s*\*+\s?", "", text)
    if re.search(r"[A-Za-z0-9]", text):
        return text.strip()
    # Punctuation-only is syntax and drops out, except a rule of six or more, which is a banner
    # and the thing worth reporting.
    return text.strip() if BANNER.match(text.strip()) else ""


def blocks(path: Path, spec: dict) -> list[tuple[int, list[str], str]]:
    """Every comment block: its first line number, its prose lines, and the code beneath it."""
    try:
        lines = path.read_text(errors="replace").splitlines()
    except (OSError, UnicodeDecodeError):
        return []

    found: list[tuple[int, list[str], str]] = []
    line_open = spec["line"]
    block_open, block_close = spec["block"] if spec["block"] else (None, None)
    i = 0

    while i < len(lines):
        raw = lines[i]
        stripped = raw.strip()

        started = False
        if block_open and stripped.startswith(block_open):
            start, body = i, []
            while i < len(lines):
                body.append(lines[i])
                if block_close in lines[i] and (i > start or lines[i].strip() != block_open):
                    break
                i += 1
            started = True
        elif line_open and stripped.startswith(line_open):
            start, body = i, []
            while i < len(lines) and lines[i].strip().startswith(line_open):
                body.append(lines[i])
                i += 1
            i -= 1
            started = True

        if started:
            # The next line that is code. Stopping at the first non-blank lands on the docblock
            # above a method, and then nothing looks like a declaration.
            openers = tuple(filter(None, [line_open, block_open, "*"]))
            following = ""
            for j in range(i + 1, min(i + 8, len(lines))):
                candidate = lines[j].strip()
                if not candidate or candidate.startswith(openers):
                    continue
                following = candidate
                break
            prose = [strip_marker(l, spec) for l in body if not PRAGMA.match(l)]
            prose = [p for p in prose if p]
            if prose:
                found.append((start + 1, prose, following))
        i += 1

    return found


def classify(prose: list[str], following: str, path: Path,
             max_block: int, max_inline: int) -> str | None:
    text = " ".join(prose)
    first = prose[0]

    if MARKER.search(text):
        return "todo"

    # An example file's job is to explain, so only length is judged there. A commented-out setting
    # is the idiom rather than a mistake: it shows an optional key without overriding the default,
    # which a blank value would not, since an empty variable is read as "" rather than as absent.
    if is_example_file(path):
        # The commented setting is the thing being shown, not words about it.
        explanation = [line for line in prose if not CODE_SHAPED.search(line)]
        return "verbose_example" if len(explanation) > max_inline else None

    if GENERATED.search(text):
        return "generated_boilerplate"
    # A banner is often three lines: rule, label, rule. Judging only single-line blocks misses
    # the shape it actually takes.
    if all(BANNER.match(line) for line in prose):
        return "banner"
    if len(prose) > 1 and any(BANNER.match(line) for line in prose):
        return "banner"
    if len(prose) == 1 and CODE_SHAPED.search(first):
        return "commented_code"
    # A signpost sits above a group of declarations. A word or two above a statement is a legend
    # for the line beneath it, which is a different thing and often worth keeping.
    if (len(prose) == 1 and SECTION_LABEL.match(first) and DECLARATION.search(following)
            and not first.rstrip().endswith((".", ":", "?"))):
        return "section_label"

    declaration = DECLARATION.search(following)
    if declaration and len(prose) >= 2:
        opener, name = words(first), set(words(declaration.group(1)))
        if opener and name and len(opener) <= 12:
            covered = sum(1 for w in opener if w in name or any(w in n or n in w for n in name))
            if covered / len(opener) >= 0.5:
                return "restates"

    if len(prose) == 1 and following:
        comment, code = words(first), set(words(following))
        if comment and code and len(comment) <= 9:
            covered = sum(1 for w in comment if w in code or any(w in c or c in w for c in code))
            if covered / len(comment) >= 0.7:
                return "restates"

    limit = max_block if len(prose) > 2 else max_inline
    if len(prose) > max(limit, max_inline):
        return "too_long"
    return None


def audit(root: Path, max_block: int, max_inline: int) -> tuple[list[Note], dict]:
    notes: list[Note] = []
    density: dict[str, tuple[int, int]] = {}

    for path in sorted(root.rglob("*")):
        if not path.is_file() or any(part in SKIP_DIRS for part in path.parts):
            continue
        spec = syntax_for(path)
        if spec is None:
            continue

        try:
            head = path.read_text(errors="replace")[:2000]
        except (OSError, UnicodeDecodeError):
            continue
        if GENERATED.search(head):
            continue

        prose_lines = 0
        for line, prose, following in blocks(path, spec):
            prose_lines += len(prose)
            category = classify(prose, following, path, max_block, max_inline)
            if category:
                notes.append(Note(
                    path=str(path.relative_to(root)), line=line, category=category,
                    height=len(prose), text=" ".join(prose)[:140], following=following[:90],
                ))

        total = sum(1 for l in path.read_text(errors="replace").splitlines() if l.strip())
        if total:
            density[str(path.relative_to(root))] = (prose_lines, total)

    return notes, density


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("path", nargs="?", default=".")
    parser.add_argument("--category", help="comma-separated categories to show")
    parser.add_argument("--format", choices=["text", "json"], default="text")
    parser.add_argument("--max-block", type=int, default=4, help="prose lines allowed on a docblock")
    parser.add_argument("--max-inline", type=int, default=2, help="prose lines allowed inline")
    parser.add_argument("--top", type=int, default=10, help="how many dense files to list")
    args = parser.parse_args()

    root = Path(args.path).resolve()
    if not root.exists():
        return parser.error(f"{root} does not exist")

    notes, density = audit(root, args.max_block, args.max_inline)

    if args.category:
        wanted = {c.strip() for c in args.category.split(",")}
        notes = [n for n in notes if n.category in wanted]

    prose_total = sum(p for p, _ in density.values())
    code_total = sum(t for _, t in density.values()) or 1
    failing = [n for n in notes if n.category in FAILING]

    if args.format == "json":
        print(json.dumps({
            "root": str(root),
            "prose_comment_lines": prose_total,
            "lines_scanned": code_total,
            "density_percent": round(prose_total * 100 / code_total, 1),
            "failing": len(failing),
            "advisory": len(notes) - len(failing),
            "notes": [asdict(n) for n in notes],
        }, indent=2))
        return 1 if failing else 0

    by_category: dict[str, list[Note]] = {}
    for note in notes:
        by_category.setdefault(note.category, []).append(note)

    headings = {
        "todo": "Markers. It is an issue or it does not exist",
        "commented_code": "Commented-out code. Version control remembers it",
        "section_label": "Section labels. A file needing signposting needs splitting",
        "banner": "Banners and separators",
        "generated_boilerplate": "Generated boilerplate, left behind",
        "restates": "Restates the code or the declaration beneath it",
        "too_long": f"Past the shape: over {args.max_block} lines on a block, {args.max_inline} inline",
        "verbose_example": f"Example file explaining at more than {args.max_inline} lines",
    }

    for category in ["todo", "commented_code", "section_label", "banner",
                     "generated_boilerplate", "restates", "too_long", "verbose_example"]:
        found = by_category.get(category)
        if not found:
            continue
        print(f"\n{headings[category]}  ({len(found)})")
        for note in found[:40]:
            print(f"  {note.path}:{note.line}")
            print(f"      {note.text[:110]}")
            if note.category == "restates" and note.following:
                print(f"      -> {note.following[:90]}")
        if len(found) > 40:
            print(f"  ... and {len(found) - 40} more")

    if density:
        print(f"\nDensest files, where reading for a worthwhile *why* pays first:")
        ranked = sorted(((p, v) for p, v in density.items() if v[0]),
                        key=lambda kv: -kv[1][0] / max(kv[1][1], 1))
        for path, (prose, total) in ranked[:args.top]:
            print(f"  {prose * 100 // max(total, 1):>3}%  {prose:>4} prose / {total:>5} lines  {path}")

    print(f"\n{prose_total} prose comment lines in {len(density)} files, "
          f"{prose_total * 100 / code_total:.1f}% of {code_total} lines.")
    print(f"{len(failing)} to remove, {len(notes) - len(failing)} to read and judge.")

    if not failing and not notes:
        print("Nothing mechanically wrong. Whether the surviving comments earn their place "
              "is a question only a reader answers.")

    return 1 if failing else 0


if __name__ == "__main__":
    sys.exit(main())
